/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan;

/**
 *
 * @author Tiara
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

public class FormPeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form FormPeminjaman
     */
   
    private final DefaultTableModel modelDaftarBuku;
    private final DefaultTableModel modelDaftarPinjaman;
    private ArrayList<BukuDipinjam> daftarPinjaman;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public FormPeminjaman(){
        initComponents();
        
        modelDaftarBuku = new DefaultTableModel(new Object[]{"Daftar Buku"},0);
        modelDaftarPinjaman = new DefaultTableModel(new Object[]{"Daftar Pinjaman","Lama"},0);
        
        jTableDaftarBuku.setModel(modelDaftarBuku);
        jTableDaftarPinjaman.setModel(modelDaftarPinjaman);
        
        daftarPinjaman = new ArrayList<>();
    }
    
    public void tampilkan(){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldInput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDaftarBuku = new javax.swing.JTable();
        jButtonPinjam = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDaftarPinjaman = new javax.swing.JTable();
        jButtonKonfirmasi = new javax.swing.JButton();
        jTextFieldLama = new javax.swing.JTextField();
        jButtonUbahLama = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInputActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableDaftarBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Daftar Buku"
            }
        ));
        jScrollPane1.setViewportView(jTableDaftarBuku);

        jButtonPinjam.setText("Pinjam");
        jButtonPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPinjamActionPerformed(evt);
            }
        });

        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jTableDaftarPinjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Daftar Pinjaman", "Lama"
            }
        ));
        jScrollPane2.setViewportView(jTableDaftarPinjaman);

        jButtonKonfirmasi.setText("Konfirmasi");
        jButtonKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKonfirmasiActionPerformed(evt);
            }
        });

        jTextFieldLama.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonUbahLama.setText("Edit Lama");
        jButtonUbahLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahLamaActionPerformed(evt);
            }
        });

        jLabel1.setText("Judul Buku");

        jLabel2.setText("Durasi (hari)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLama, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUbahLama)
                        .addGap(15, 15, 15)
                        .addComponent(jButtonKonfirmasi)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPinjam))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonUbahLama)
                        .addComponent(jButtonBatal))
                    .addComponent(jButtonKonfirmasi))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPinjamActionPerformed
        int selectedRow = jTableDaftarBuku.getSelectedRow();
        
        if(selectedRow >= 0){
            String judul = (String) modelDaftarBuku.getValueAt(selectedRow,0);
            
            try {
            int lama = Integer.parseInt(jTextFieldLama.getText());
            
            if (lama > 3){
                JOptionPane.showMessageDialog(this, "Lama waktu peminjaman maksimal 3 hari");
            }else{
                Buku buku = new Buku(judul);
                BukuDipinjam bukuDipinjam = new BukuDipinjam(buku,lama);
                
                daftarPinjaman.add(bukuDipinjam);
                modelDaftarPinjaman.addRow(new Object[]{judul, lama});
                
                jTextFieldLama.setText("");
            }
            }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this,"Masukkan lama peminjaman dalam bentuk angka");
        }
        }else{
            JOptionPane.showMessageDialog(this,"Pilih buku yang akan dipinjam terlebih dahulu");
        }
    }//GEN-LAST:event_jButtonPinjamActionPerformed
      
    private void jButtonKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKonfirmasiActionPerformed
        if (daftarPinjaman.size() > 10){
            JOptionPane.showMessageDialog(this,"Jumlah buku yang dipinjam melebihi batas maksimal 10 buku");
        }else{
            for (BukuDipinjam bukuDipinjam : daftarPinjaman){
                Perpustakaan.controllerPeminjaman.pinjam(bukuDipinjam);
            }
            
            JOptionPane.showMessageDialog(this, "Peminjaman Buku Anda telah dikonfirmasi");
            
            modelDaftarPinjaman.setRowCount(0);
            daftarPinjaman.clear();
        }
    }//GEN-LAST:event_jButtonKonfirmasiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String judul = jTextFieldInput.getText();
        ArrayList<Buku> hasilPencarian = Perpustakaan.controllerPeminjaman.cariBuku(judul);
        
        modelDaftarBuku.setRowCount(0);
        
        for(Buku buku : hasilPencarian){
            modelDaftarBuku.addRow(new Object[]{buku.judul});
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        int selectedRow = jTableDaftarPinjaman.getSelectedRow();
        
        if (selectedRow >= 0){
            daftarPinjaman.remove(selectedRow);
            modelDaftarPinjaman.removeRow(selectedRow);
        }
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jTextFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInputActionPerformed

    private void jButtonUbahLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahLamaActionPerformed
        int selectedRow = jTableDaftarPinjaman.getSelectedRow();
        
        if(selectedRow >= 0){
            try {
            int lamaBaru = Integer.parseInt(jTextFieldLama.getText());
                if(lamaBaru >3){
                JOptionPane.showMessageDialog(this,"Lama waktu peminjaman maksimal 3 hari");
                }     else{
                daftarPinjaman.get(selectedRow).setLama(lamaBaru);
                modelDaftarPinjaman.setValueAt(lamaBaru, selectedRow, 1);
                }       
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Lama peminjaman dalam bentuk angka");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih buku di daftar pinjaman terlebih dahulu");
        }
    }//GEN-LAST:event_jButtonUbahLamaActionPerformed
   

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonKonfirmasi;
    private javax.swing.JButton jButtonPinjam;
    private javax.swing.JButton jButtonUbahLama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDaftarBuku;
    private javax.swing.JTable jTableDaftarPinjaman;
    private javax.swing.JTextField jTextFieldInput;
    private javax.swing.JTextField jTextFieldLama;
    // End of variables declaration//GEN-END:variables
}
