/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;


public class HalamanUtamaUI extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HalamanUtamaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuPencarian = new javax.swing.JMenu();
        menuPeminjaman = new javax.swing.JMenu();
        menuDonasiBuku = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPencarian.setText("Pencarian");
        menuPencarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPencarianMouseClicked(evt);
            }
        });
        menuPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPencarianActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuPencarian);

        menuPeminjaman.setText("Peminjaman");
        menuPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPeminjamanMouseClicked(evt);
            }
        });
        menuPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPeminjamanActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuPeminjaman);

        menuDonasiBuku.setText("Donasi Buku");
        menuDonasiBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDonasiBukuMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDonasiBuku);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPencarianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPencarianMouseClicked
        Perpustakaan.controllerPencarian = new PencarianController();
        Perpustakaan.controllerPencarian.showFormPencarian();
    }//GEN-LAST:event_menuPencarianMouseClicked

    private void menuPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPencarianActionPerformed

    private void menuPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPeminjamanActionPerformed
        
    }//GEN-LAST:event_menuPeminjamanActionPerformed

    private void menuPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPeminjamanMouseClicked
        Perpustakaan.controllerPeminjaman = new PeminjamanController();
        Perpustakaan.controllerPeminjaman.showFormPeminjaman();
    }//GEN-LAST:event_menuPeminjamanMouseClicked

    private void menuDonasiBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDonasiBukuMouseClicked
        // TODO add your handling code here:
        Perpustakaan.controllerDonasi = new DonasiBukuController();
        Perpustakaan.controllerDonasi.showFormDonasiBuku();
    }//GEN-LAST:event_menuDonasiBukuMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuDonasiBuku;
    private javax.swing.JMenu menuPeminjaman;
    private javax.swing.JMenu menuPencarian;
    // End of variables declaration//GEN-END:variables
}
